name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    null


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
        #      - name: Clippy
        #        run: cargo clippy --all-targets
      - name: Test without features
        run: cargo test --no-default-features
      - name: Rustfmt
        run: cargo fmt -- --check
